spring:
  application:
    name: heal
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:44364
          jwk-set-uri: http://localhost:44364/.well-known/jwks
          use-strict-type-checks: false

server:
  address: 0.0.0.0
  port: 60408

logging:
  level:
    org.springframework.security: DEBUG