spring:
  application:
    name: heal
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:44364
          jwk-set-uri: http://localhost:44364/.well-known/jwks
          use-strict-type-checks: false
  datasource:
    url: jdbc:mysql://192.168.5.245:3306/heal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # Mapper XML 文件路径（支持子目录）
  type-aliases-package: com.his.heal.entity         # 实体类包路径（可选）

server:
  address: 0.0.0.0
  port: 60408

logging:
  level:
    org.springframework.security: DEBUG