spring:
  application:
    name: heal
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:44364
          jwk-set-uri: http://localhost:44364/.well-known/jwks
          use-strict-type-checks: false
  datasource:
    url: jdbc:mysql://192.168.5.245:3306/heal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  messages:
    basename: message/messages
    encoding: UTF-8
  data:
    redis:
      host: 192.168.5.245
      prot: 6379

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # Mapper XML 文件路径（支持子目录）
  type-aliases-package: com.his.heal.entity         # 实体类包路径（可选）

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    url: /v3/api-docs
    path: /swagger-ui.html
  packages-to-scan: com.his.heal.controller  # 指定扫描哪些包下的 controller
  default-flat-param-object: false
custom:
  jwt:
    jwkSetUri: http://localhost:44364/.well-known/jwks
    requestMatchers:
      - /api/v1/test
      - /api/v1/test/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /api/v1/i18n